---
title: "GEO 880 - week 4 v2 - Exercise A: Segmentation"
author: "Lars Weidinger"
date: "today"
format: 
  html:
    fig_caption: true
    fig-align: center
    highlight: tango
    number-sections: false
    code-fold: true
    theme: lumen
    embed-resources: true
    toc: true
    toc_depth: 2
    toc_float: true
execute:                      # Set global options for execution of code blocks
  echo: true                  # False = no code printed
  warning: false
  message: false
editor: visual
---

<!-- The following html code fragment produces fully justified text alignment -->

```{=html}
<style>
body {text-align: justify}
</style>
```

# Preliminaries

## Set Options

```{r}
options(warning = FALSE)    # Don't show warnings
```

## Install or Load packages

```{r}
#| code-fold: show
library(pacman)

# Load and if not found in the library will attempt to install the package
pacman::p_load(here,
               sf,
               readr,
               tmap,
               dplyr,
               ggplot2,
               tidyr,
               install = TRUE)
```

## Store relevant CRS

```{r}
crs_lv03  <- 21781
crs_lv95  <- 2056
crs_wgs84 <- 4326
```

# Load & Prepare Data
```{r}
wildschwein <- read_delim("data/wildschwein_BE_2056.csv", ",")

# Careful! What Timezone is assumed? --> UTC
ruth <- wildschwein |>
    st_as_sf(coords = c("E", "N"), crs = crs_lv95, remove = FALSE) |>
    filter(
      TierName == "Ruth", 
      DatetimeUTC >= "2015-07-01", 
      DatetimeUTC < "2015-07-05"
      )
```

# Task 1: Calculate distances
## a): Specify a temporal window 
In the above dataset, the sampling interval is 15 minutes. If we take a temporal window of 90 minutes, that would mean including 6 fixes. 


## b): Measure the distance to every point within v
```{r}
distance_by_element <- function(later, now) {
  as.numeric(
    st_distance(later, now, by_element = TRUE)
  )
}

ruth <- ruth |>
    mutate(
      nMinus3 = distance_by_element(lag(geometry, 3), geometry),  # distance to pos -45 min
        nMinus2 = distance_by_element(lag(geometry, 2), geometry),  # distance to pos -30 min
        nMinus1 = distance_by_element(lag(geometry, 1), geometry),  # distance to pos -15 min
        nPlus1  = distance_by_element(geometry, lead(geometry, 1)), # distance to pos +15 min
        nPlus2  = distance_by_element(geometry, lead(geometry, 2)),  # distance to pos +30 min
      nPlus3  = distance_by_element(geometry, lead(geometry, 3))  # distance to pos +45 min
    )
```

```{r}
# calculate mean distance
ruth <- ruth |>
    rowwise() |>
    mutate(
        stepMean = mean(c(nMinus2, nMinus1, nPlus1, nPlus2))
    ) |>
    ungroup()

ruth
```



# Task 2: Specify and apply threshold d
```{r}

```


